@startuml
left to right direction

' creates a stick figure with a displayed title in
' quotes and creates a 'code' name after the as
actor "Unregistered User" as unregistered
actor "Registered User" as registered
actor "Demonstration User" as demo
actor Administrator as admin

' a package is a way to group all of the use cases
' under the website name
package NgunnawalWebsite {
    usecase "User Registration" as UC1
    usecase "User Login" as UC2
    usecase "User Logout" as UC3
    usecase "View Account Details" as UC4
    usecase "Reset Password" as UC5
    usecase "Access Gallery" as UC6
    usecase "Upload Photos" as UC7
    usecase "Download Photos" as UC8
    usecase "Feedback Messages" as UC9
    usecase "Error Messages" as UC10
    usecase "Access Logs" as UC11
}

' this is directing actors to the use case with an arrow,
' using the 'code' names of each element
unregistered --> UC1
unregistered --> UC2
unregistered --> UC6
unregistered --> UC9
unregistered --> UC10

registered --> UC2
registered --> UC3
registered --> UC4
registered --> UC5
registered --> UC6
registered --> UC7
registered --> UC8
registered --> UC9
registered --> UC10

demo --> UC3
demo --> UC6

admin --> UC2
admin --> UC3
admin --> UC5
admin --> UC6
admin --> UC7
admin --> UC8
admin --> UC9
admin --> UC10
admin --> UC11


@enduml